<?= $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="robots" content="noindex">
<?php
echo $this->headTitle($this->appTitle.' API Server');

echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');

echo $this->headLink(['rel' => 'icon', 'type' => 'image/png', 'href' => $this->basePath('/img/favicon.png')])
    ->prependStylesheet($this->basePath('/api-tools/css/main.min.css'))
    ->prependStylesheet($this->basePath('/api-tools/css/bootstrap.min.css'));

echo $this->headScript()
    ->prependFile($this->basePath('/api-tools/js/bootstrap.min.js'))
    ->prependFile($this->basePath('/api-tools/js/jquery.min.js'));
?>
    <style>
        html, body {
            background: #1d1e31;,
            color: #fff;
        }

        span, div, p {
            color: #fff;
        }
    </style>
</head>
<body>
    <header>
        <div class="container">
            <img src="https://swissfaucet.io/img/logo.4afd33a7.png" style="max-width: 72px; position: absolute; top:8px;" />
            <h3 style="max-width: 72px; position: absolute; top:0; margin-left: 80px;">Swissfaucet.io</h3>
        </div>
    </header>
    <div class="container">
        <?= $this->content ?>
    </div>
    <footer>
        <hr/>
        <div class="container center-block"><div class="row">
            <div class="col-sm-4">
                &copy; <?= date('Y') ?> <a href="https://swissfaucet.io">
                    Swissfaucet.io
                </a>
            </div>
        </div></div>
    </footer>
    <?= $this->inlineScript() ?>
</body>
</html>
